apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-api-cert
  namespace: standard
spec:
  secretName: fastapi-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: yamlkubectl.course-datascientest.cloudns.ch        # Update with your domain
  dnsNames:
  - yamlkubectl.course-datascientest.cloudns.ch
  - yamlkubectl.course-datascientest.cloudns.ch
