apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Set the ACME server URL for production
    server: https://acme-v02.api.letsencrypt.org/directory
    email: srisurabhi5@gmail.com       # Update with your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
